Config = {
    Default = 'none', -- The default entity set for when your server restarts.
    Sets = {
        basketball = {'mba_tribune', 'mba_tarps', 'mba_basketball', 'mba_jumbotron'},
        boxing = {'mba_tribune', 'mba_tarps', 'mba_fighting', 'mba_boxing', 'mba_jumbotron'},
        concert = {'mba_tribune', 'mba_tarps', 'mba_backstage', 'mba_concert', 'mba_jumbotron'},
        curling = {'mba_tribune', 'mba_chairs', 'mba_curling'},
        derby = {'mba_cover', 'mba_terrain', 'mba_derby', 'mba_ring_of_fire'},
        fameorshame = {'mba_tribune', 'mba_tarps', 'mba_backstage', 'mba_fameorshame', 'mba_jumbotron'},
        fashion = {'mba_tribune', 'mba_tarps', 'mba_backstage', 'mba_fashion', 'mba_jumbotron'},
        football = {'mba_tribune', 'mba_chairs', 'mba_field', 'mba_soccer'},
        icehockey = {'mba_tribune', 'mba_chairs', 'mba_field', 'mba_hockey'},
        gokarta = {'mba_cover', 'mba_gokart_01'},
        gokartb = {'mba_cover', 'mba_gokart_02'},
        trackmaniaa = {'mba_trackmania_01', 'mba_cover'},
        trackmaniab = {'mba_trackmania_02', 'mba_cover'},
        trackmaniac = {'mba_trackmania_03', 'mba_cover'},
        trackmaniad = {'mba_trackmania_04', 'mba_cover'},
        mma = {'mba_tribune', 'mba_tarps', 'mba_fighting', 'mba_mma', 'mba_jumbotron'},
        none = {'mba_tribune', 'mba_tarps', 'mba_jumbotron'},
        paintball = {'mba_tribune', 'mba_chairs', 'mba_paintball', 'mba_jumbotron'},
        rocketleague = {'mba_tribune', 'mba_chairs', 'mba_rocketleague'},
        wrestling = {'mba_tribune', 'mba_tarps', 'mba_fighting', 'mba_wrestling', 'mba_jumbotron'}
    },
    Signs = {
        basketball = 'gabz_ipl_mba_sign_basketball',
        boxing = 'gabz_ipl_mba_sign_boxing',
        concert = 'gabz_ipl_mba_sign_concert',
        curling = 'gabz_ipl_mba_sign_curling',
        derby = 'gabz_ipl_mba_sign_derby',
        fameorshame = 'gabz_ipl_mba_sign_fameorshame',
        fashion = 'gabz_ipl_mba_sign_fashion',
        football = 'gabz_ipl_mba_sign_soccer',
        icehockey = 'gabz_ipl_mba_sign_icehockey',
        gokarta = 'gabz_ipl_mba_sign_gokart',
        gokartb = 'gabz_ipl_mba_sign_gokart',
        trackmaniaa = 'gabz_ipl_mba_sign_banditomania',
        trackmaniab = 'gabz_ipl_mba_sign_banditomania',
        trackmaniac = 'gabz_ipl_mba_sign_banditomania',
        trackmaniad = 'gabz_ipl_mba_sign_banditomania',
        mma = 'gabz_ipl_mba_sign_mma',
        paintball = 'gabz_ipl_mba_sign_paintball',
        rocketleague = 'gabz_ipl_mba_sign_banditoleague',
        wrestling = 'gabz_ipl_mba_sign_wrestling'
    },
    Removals = {
        interiors = {'mba_trackmania_04', 'mba_trackmania_03', 'mba_trackmania_02', 'mba_trackmania_01', 'mba_gokart_02', 'mba_gokart_01', 'mba_hockey', 'mba_field', 'mba_soccer', 'mba_rocketleague', 'mba_curling', 'mba_tribune', 'mba_cover', 'mba_tarps', 'mba_chairs', 'mba_basketball', 'mba_derby', 'mba_paintball', 'mba_fighting', 'mba_wrestling', 'mba_mma', 'mba_boxing', 'mba_backstage', 'mba_concert', 'mba_fashion', 'mba_fameorshame', 'mba_ring_of_fire', 'mba_jumbotron', 'mba_terrain'},
        signs = {'gabz_ipl_mba_sign_basketball', 'gabz_ipl_mba_sign_boxing', 'gabz_ipl_mba_sign_concert', 'gabz_ipl_mba_sign_curling', 'gabz_ipl_mba_sign_derby', 'gabz_ipl_mba_sign_fameorshame', 'gabz_ipl_mba_sign_fashion', 'gabz_ipl_mba_sign_soccer', 'gabz_ipl_mba_sign_icehockey', 'gabz_ipl_mba_sign_gokart', 'gabz_ipl_mba_sign_banditomania', 'gabz_ipl_mba_sign_mma', 'gabz_ipl_mba_sign_paintball', 'gabz_ipl_mba_sign_banditoleague', 'gabz_ipl_mba_sign_wrestling'}
    }
}